- hosts: bulkhead 
  become: true
  tasks:
  - name: Update repositories cache and install "PXE" package
    apt:
      pkg:
      - pxelinux
      - syslinux-common
      update_cache: yes
      state: present
