all:
  hosts:
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  children: 
    server: 
      hosts:
        bulkhead:
    desktop: 
      hosts:
        bumblebee:
        asus:
        ironhide:
    MythtvFrontend_machines: 
      hosts:
        bumblebee:
        asus:
    MythtvMaster_machines: 
      hosts:
        ironhide:
