---
- name: "Installation mythtv frontend "
  hosts: MythtvFrontend_machines
  become: true
  roles:
    - role: "MythTV"
      mythtv_type_install: frontend 

- name: "Installation mythtv frontend et backend"
  hosts: MythtvMaster_machines 
  become: true
  roles:
    - role: "MythTV"
      mythtv_type_install: full
