---
# tasks file for MythTV
# Add mythtv stable repository from PPA and install its signing key.
- name: ppa pour Mythtv
  apt_repository:
    repo: ppa:mythbuntu/31


- name: "isntall MythTV full backend et frontend"
  apt:
    name:
      - mythtv
    update_cache: yes
    state: present
  when: ( mythtv_type_install == "full")

- name: "isntall MythTV frontend"
  apt:
    name:
      - mythtv-frontend 
    update_cache: yes
    state: present
  when: ( mythtv_type_install == "frontend")


